In [ ]:
# Step 1: Database Creation
# Create a new SQLite database named library.db and define the table
connection = sqlite3.connect('library.db')
cursor = connection.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS Books (
    Title TEXT,
    Author TEXT,
    Year_Published INTEGER,
    Genre TEXT
)
''')

# Step 2: Insert Data
books_data = [
    ("To Kill a Mockingbird", "Harper Lee", 1960, "Fiction"),
    ("1984", "George Orwell", 1949, "Dystopian"),
    ("The Great Gatsby", "F. Scott Fitzgerald", 1925, "Classic")
]
cursor.executemany('INSERT INTO Books (Title, Author, Year_Published, Genre) VALUES (?, ?, ?, ?)', books_data)

# Step 3: Update Data
cursor.execute('UPDATE Books SET Year_Published = ? WHERE Title = ?', (1950, "1984"))

# Step 4: Query Data
cursor.execute('SELECT Title, Author FROM Books WHERE Genre = "Dystopian"')
dystopian_books = cursor.fetchall()

# Step 5: Delete Data
cursor.execute('DELETE FROM Books WHERE Year_Published < 1950')

# Step 6: Add a new column "Rating" and update data
cursor.execute('ALTER TABLE Books ADD COLUMN Rating REAL')
ratings = [
    (4.8, "To Kill a Mockingbird"),
    (4.7, "1984"),
    (4.5, "The Great Gatsby")
]
for rating, title in ratings:
    cursor.execute('UPDATE Books SET Rating = ? WHERE Title = ?', (rating, title))

# Step 7: Advanced Query - Retrieve all books sorted by Year_Published in ascending order
cursor.execute('SELECT * FROM Books ORDER BY Year_Published ASC')
sorted_books = cursor.fetchall()

# Commit changes and close the connection
connection.commit()
connection.close()

# Display results
{
    "Dystopian Books": dystopian_books,
    "Books Sorted by Year_Published (Asc)": sorted_books
}